### ISSUE TITLE
Add support to Python 3.4

### ISSUE THREAD

**Issue by maxxer** [g2p/blocks#14]
Ubuntu 14.04 (out in few weeks) introduced Python 3.4.
Please add support for this newer version

**Comment by g2p** [comment]
I did a quick and dirty Travis run and nothing broke, as expected since Python 3.4 has very few incompatible changes. Ubuntu 14.04 has a few changes beyond that (udev always requires testing, and someone posted about a supermin change).

**Comment by maxxer** [comment]
do you have any plan for supporting ubuntu 14.04? thanks

**Comment by mf-lit** [comment]
I'd also like to request Python 3.4 support. Thanks.

**Comment by kislyuk** [comment]
+1

**Comment by ozmad** [comment]
Just a simple workaround if you need it:
install python3.3
taken from: http://linuxg.net/how-to-install-python-3-3-on-ubuntu-13-04-12-10-and-12-04/
    sudo apt-get install python-software-properties
    sudo add-apt-repository ppa:fkrull/deadsnakes
    sudo apt-get update
    sudo apt-get install python3.3

**Comment by jelabarre59** [comment]
Also in favor of python 3.4 support.  Linux Mint 17.3 has Python 3.4, who knows when 3.5 may come out as well.

**Comment by alexwijoyo** [comment]
Hi,
I try to run blocks on Ubuntu 16.04.
I've followed @ozmad instruction to install python3.3. But it seems the pip-3.3 still didn't work. After I ran: 
`
type pip-3.3 || alias pip-3.3='python3.3 -m pip.runner'
pip-3.3 --version
/usr/bin/python3.3: No module named pip.runner
`
But I have a working pip3:
`
pip3 --version
pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.5)
`
Then I tried the blocks installation using pip3:
`
pip3 install --user -r <(wget -O- https://raw.github.com/g2p/blocks/master/requirements.txt)
--2018-06-20 12:11:11--  https://raw.github.com/g2p/blocks/master/requirements.txt
Resolving raw.github.com (raw.github.com)... 151.101.8.133
Connecting to raw.github.com (raw.github.com)|151.101.8.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/g2p/blocks/master/requirements.txt [following]
--2018-06-20 12:11:11--  https://raw.githubusercontent.com/g2p/blocks/master/requirements.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.8.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.8.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 211 [text/plain]
Saving to: ‘STDOUT’

-                   100%[===================>]     211  --.-KB/s    in 0s      

2018-06-20 12:11:12 (65.5 MB/s) - written to stdout [211/211]

Obtaining blocks from git+https://github.com/g2p/blocks.git@master#egg=blocks (from -r /dev/fd/63 (line 1))
  Updating ./src/blocks clone (to master)
Obtaining python-augeas from git+https://github.com/g2p/python-augeas.git@v0.4.2a1#egg=python-augeas (from -r /dev/fd/63 (line 2))
  Updating ./src/python-augeas clone (to v0.4.2a1)
Collecting pyparted from https://github.com/g2p/pyparted/archive/pyparted-3.10a1.tar.gz#egg=pyparted (from -r /dev/fd/63 (line 3))
Collecting maintboot (from blocks->-r /dev/fd/63 (line 1))
Installing collected packages: maintboot, python-augeas, pyparted, blocks
  Running setup.py develop for python-augeas
  Running setup.py develop for blocks
Successfully installed blocks-0.1.4 maintboot-0.1.0 pyparted-3.10.7 python-augeas-0.4.2a1
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`
I have blocks and maintboot executables below:
`
ls .local/bin -l
total 8
-rwxrwxr-x 1 it it  276 Jun 20 12:11 blocks
-rwxrwxr-x 1 it it 2813 Jun 20 12:11 maintboot
`
I copied both executables to /usr/local/bin and execute blocks:
`
sudo blocks to-bcache --maintboot /dev/ubuntu-vg/root --join b2967e2f-67a2-45d4-ba70-85ec341db39c
supermin command not found, please install supermin (preferred) or febootstrap (obsolete)
Traceback (most recent call last):
  File "/usr/local/bin/blocks", line 9, in <module>
    load_entry_point('blocks', 'console_scripts', 'blocks')()
  File "/home/it/src/blocks/blocks/__main__.py", line 2012, in script_main
    sys.exit(main())
  File "/home/it/src/blocks/blocks/__main__.py", line 1678, in main
    return args.action(args)
  File "/home/it/src/blocks/blocks/__main__.py", line 1758, in cmd_to_bcache
    device, 'to-bcache', debug=args.debug, join=args.join)
  File "/home/it/src/blocks/blocks/__main__.py", line 1780, in call_maintboot
    + ['--append', 'BLOCKS_ARGS=' + encoded])
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['maintboot', '--pkgs', 'python3-blocks', 'util-linux', 'dash', 'mount', 'base-files', 'libc-bin', 'nilfs-tools', 'reiserfsprogs', 'xfsprogs', 'e2fsprogs', 'btrfs-tools', 'lvm2', 'cryptsetup-bin', 'bcache-tools', '--initscript', '/home/it/src/blocks/blocks/maintboot.init', '--append', 'BLOCKS_ARGS=%7B%22debug%22%3A%20false%2C%20%22device%22%3A%20%22088de93d-ec73-4e20-8a73-339c639a08fe%22%2C%20%22join%22%3A%20%22b2967e2f-67a2-45d4-ba70-85ec341db39c%22%2C%20%22command%22%3A%20%22to-bcache%22%7D']' returned non-zero exit status 2
`
Does anyone know how to install supermin 4 on Ubuntu 16.04 so I can run blocks?
IMHO blocks is an important companion tool for bcache. Too bad the development is stopped. I've tried the Ubuntu Raring Live CD alternative to install blocks but somehow the live cd just showing the dots progress bar.

**Comment by bjmgeek** [comment]
Python 3.6 is out now.  I'm trying to get blocks to build on it.

**Comment by modem7** [comment]
do we know if this works with Python 3.5/3.6?
