### ISSUE TITLE
'to-bcache' fails with assertion error

### ISSUE THREAD

**Issue by kevle** [g2p/blocks#18]
Hey, I'm running into a problem I can't quite figure out on my own.
I have a LVM2 volumegroup 'mass_storage' with the logical volume 'storage' which I try to convert into a bcache thingy.

Here is the output:
# :~$ sudo blocks to-bcache /dev/mass_storage/storage

The filesystem (xfs) leaves enough room, no need to shrink it
Copying the bcache superblock... ok
Loading LVM metadata... ok
Traceback (most recent call last):
  File "/usr/bin/blocks", line 9, in <module>
    load_entry_point('blocks==0.1.4', 'console_scripts', 'blocks')()
  File "/usr/lib/python3/dist-packages/blocks/**main**.py", line 2002, in script_main
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/blocks/**main**.py", line 1668, in main
    return args.action(args)
  File "/usr/lib/python3/dist-packages/blocks/**main**.py", line 1751, in cmd_to_bcache
    device=device, debug=args.debug, progress=progress, join=args.join)
  File "/usr/lib/python3/dist-packages/blocks/**main**.py", line 1507, in lv_to_bcache
    device=device, size=device.size, debug=debug, forward=False)
  File "/usr/lib/python3/dist-packages/blocks/**main**.py", line 1424, in rotate_lv
    assert all(ch in ASCII_ALNUM_WHITELIST for ch in vgname), vgname
AssertionError: mass_storage

**Comment by kevle** [comment]
Turns out I should read error messages more carefully. After renaming the volume it works. Sorry.

**Comment by g2p** [comment]
I think the assert is to make parsing some lvm output unambiguous. Not sure if I should relax it or not.
Congrats on being resourceful.
