### ISSUE TITLE
Cannot convert to LVM

### ISSUE THREAD

**Issue by TheOneValen** [g2p/blocks#30]
Trying to convert an ext4 volume on /dev/sdb to lvm and get the following error (after successful resize it seems):
```
The filesystem (ext4) leaves enough room, no need to shrink it
Copying 4194304 bytes from pos 0 to pos 4000778813440... ok
Preparing LVM metadata... Traceback (most recent call last):
  File "/usr/bin/blocks", line 9, in <module>
    load_entry_point('blocks==0.1.4', 'console_scripts', 'blocks')()
  File "/usr/lib64/python3.4/site-packages/blocks-0.1.4-py3.4.egg/blocks/__main__.py", line 2012, in script_main
  File "/usr/lib64/python3.4/site-packages/blocks-0.1.4-py3.4.egg/blocks/__main__.py", line 1678, in main
  File "/usr/lib64/python3.4/site-packages/blocks-0.1.4-py3.4.egg/blocks/__main__.py", line 1886, in cmd_to_lvm
  File "/usr/lib64/python3.4/contextlib.py", line 283, in enter_context
    result = _cm_type.__enter__(cm)
  File "/usr/lib64/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/lib64/python3.4/site-packages/blocks-0.1.4-py3.4.egg/blocks/__main__.py", line 1276, in synth_device
  File "/usr/lib64/python3.4/site-packages/blocks-0.1.4-py3.4.egg/blocks/__main__.py", line 170, in __init__
AssertionError: /dev/mapper/synthetic-7fc406e4-2a55-11e6-8ef2-00012e37f3d5
```

**Comment by jskarpe** [comment]
I'm also seeing this issue

**Comment by fl4p-old** [comment]
I had the same issue when i tried to lvmify an old swap partition. Got it working by using Python 3.3 and (I believe this was crucial) creating a ext4 fs first.
On ubuntu python 3.3 is available through PPA https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa . 
Install blocks with
```
python3.3 -m pip install --user -r <(wget -O- https://raw.github.com/g2p/blocks/master/requirements.txt)
```
