### ISSUE TITLE
Failing to convert with btrfs

### ISSUE THREAD

**Issue by Anaerin** [g2p/blocks#37]
Self-compiled (successfully) on Ubuntu Xenial (16.04.3), and I'm getting the following error:
```anaerin@mythbox:~/blocks$ sudo /home/anaerin/.local/bin/blocks to-lvm --vg-name=NAS /dev/sda1
Will shrink the filesystem (btrfs) by 4526080 bytes
Traceback (most recent call last):
  File "/home/anaerin/.local/bin/blocks", line 9, in <module>
    load_entry_point('blocks', 'console_scripts', 'blocks')()
  File "/home/anaerin/blocks/src/blocks/blocks/__main__.py", line 2012, in script_main
    sys.exit(main())
  File "/home/anaerin/blocks/src/blocks/blocks/__main__.py", line 1678, in main
    return args.action(args)
  File "/home/anaerin/blocks/src/blocks/blocks/__main__.py", line 1861, in cmd_to_lvm
    block_stack.stack_reserve_end_area(pe_newpos, progress)
  File "/home/anaerin/blocks/src/blocks/blocks/__main__.py", line 1096, in stack_reserve_end_area
    block_data.reserve_end_area_nonrec(inner_pos)
  File "/home/anaerin/blocks/src/blocks/blocks/__main__.py", line 501, in reserve_end_area_nonrec
    self._mount_and_resize(pos)
  File "/home/anaerin/blocks/src/blocks/blocks/__main__.py", line 549, in _mount_and_resize
    assert self.fssize == pos
AssertionError
```

Not sure just what is going on here. Any insight?

**Comment by Anaerin** [comment]
Having downgraded to python3.3, I've not gotten past this error. Please can you look into updating this to support Python 3.5 or newer?
